/**
 * Drift gate (SPEC §5.1 / Fase 1 DoD) + tests del normalizador.
 *
 * - "paridad real" (skipIf sin PROFILE_DATA_PATH): el archivo commiteado
 *   `profile.generated.ts` DEBE ser el output exacto del pipeline. Si editas
 *   profile-data y no corrés `npm run sync:profile` + commit, este test falla
 *   localmente (CI no tiene acceso al workspace privado → skip, D1/D14).
 *   El syncedAt del archivo commiteado se reutiliza para aislar el diff de
 *   contenido (la marca de tiempo cambia en cada sync por diseño).
 * - "shape" (siempre): el archivo existe, es AUTO-GENERATED y tiene el contrato
 *   mínimo del CV data model (SPEC §5.2).
 * - "normalizador" (siempre, fixture): dual-shape v1/v1.1 — highlights string →
 *   array, role/org → langMap, url derivada de DOI, determinismo byte a byte.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { generateAll, normalize, resolvePaths, driftReport, type CVProfile, type SyncReport } from "../../tools/sync-profile";
import { PROFILE } from "./profile.generated";

const GENERATED = resolve(process.cwd(), "src", "data", "profile.generated.ts");
const COMMITTED = readFileSync(GENERATED, "utf8");
const { workspace } = resolvePaths();

/* ──────────────────────────────────────────────
   Paridad con el workspace real (drift gate)
────────────────────────────────────────────── */

describe("paridad con profile-data (drift gate)", () => {
  it.skipIf(!workspace)("profile.generated.ts commiteado == output del pipeline", () => {
    // Reutiliza el syncedAt del archivo commiteado: aísla el diff de contenido
    // (la marca de tiempo cambia en cada sync por diseño — provenance).
    const m = COMMITTED.match(/"syncedAt": "([^"]+)"/);
    const now = m ? new Date(m[1]) : new Date(0);
    const { source } = generateAll({ now });
    expect(source).toBe(COMMITTED);
  });
});

/* ──────────────────────────────────────────────
   Shape del archivo generado (CI-safe)
────────────────────────────────────────────── */

describe("profile.generated.ts — shape", () => {
  it("es AUTO-GENERATED (nunca editar a mano)", () => {
    expect(COMMITTED).toMatch(/AUTO-GENERATED by tools\/sync-profile\.ts/);
    expect(COMMITTED).toMatch(/DO NOT EDIT/);
  });

  it("identity: nombre + links canónicos (ancla GEO)", () => {
    expect(PROFILE.identity.name).toBe("Christian Luciani");
    expect(PROFILE.identity.givenName).toBe("Christian");
    expect(PROFILE.identity.familyName).toBe("Luciani");
    expect(PROFILE.identity.location).toBeTruthy();
    expect(PROFILE.identity.links.length).toBeGreaterThanOrEqual(8);
    for (const l of PROFILE.identity.links) expect(l.url).toMatch(/^https?:|^mailto:/);
  });

  it("experience: highlights normalizados a arrays", () => {
    expect(PROFILE.experience.length).toBeGreaterThanOrEqual(6);
    for (const e of PROFILE.experience) {
      expect(e.start).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(e.end).toMatch(/^\d{4}-\d{2}-\d{2}$|^present$/);
      if (e.highlights) {
        expect(Array.isArray(e.highlights.en)).toBe(true);
        expect(e.highlights.en.length).toBeGreaterThan(0);
        for (const h of e.highlights.en) expect(h.length).toBeGreaterThan(0);
      }
    }
  });

  it("projects: evidence con claim/source (verificable)", () => {
    const kontablo = PROFILE.projects.find((p) => p.name.includes("Kontablo"));
    expect(kontablo).toBeTruthy();
    expect(kontablo!.evidence.length).toBeGreaterThanOrEqual(1);
    for (const ev of kontablo!.evidence) {
      expect(ev.claim.en).toBeTruthy();
      expect(ev.source).toMatch(/^https?:/);
    }
  });

  it("publications: url derivada de DOI; sin DOI → url vacía (v1.1 pendiente)", () => {
    expect(PROFILE.publications.length).toBeGreaterThanOrEqual(8);
    for (const p of PROFILE.publications) {
      const doi = (p as { doi?: string }).doi;
      if (doi) expect(p.url).toBe(`https://doi.org/${doi}`);
      else expect(p.url).toBe("");
    }
    const withoutDoi = PROFILE.publications.filter((p) => !(p as { doi?: string }).doi);
    expect(withoutDoi.length).toBe(2); // Hydrochars (RG) + AIChE abstract — v1.1 los resuelve
  });

  it("skills + keywords.geo (anclas semánticas GEO)", () => {
    expect(PROFILE.skills.length).toBeGreaterThanOrEqual(5);
    expect(PROFILE.keywords.geo.associations.length).toBeGreaterThanOrEqual(3);
    expect(PROFILE.keywords.geo.claims.length).toBeGreaterThanOrEqual(3);
  });

  it("source: procedencia del SSOT (GEO / auditoría)", () => {
    expect(PROFILE.source.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(PROFILE.source.repo).toContain("profile-data");
    expect(PROFILE.source.syncedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });
});

/* ──────────────────────────────────────────────
   Normalizador — dual-shape v1/v1.1 (fixture)
────────────────────────────────────────────── */

function emptyReport(): SyncReport {
  return { missingEs: [], publicationsWithoutLink: [], urlsOutsideIdentity: [] };
}

describe("normalize — v1 legacy → CV data model", () => {
  it("highlights string v1: split por '. ' preservando el separador '·' interno", () => {
    const r = emptyReport();
    const p = normalize(
      {
        identity: { name: "A B" },
        experience: [
          {
            role: "R",
            org: "O",
            start: "2020-01-01",
            end: "present",
            highlights: { en: "Alpha · beta. Gamma. Delta with 1.000 pax.", es: "Alfa · beta." }
          }
        ]
      },
      r
    );
    expect(p.experience[0].highlights?.en).toEqual(["Alpha · beta", "Gamma", "Delta with 1.000 pax"]);
    expect(p.experience[0].highlights?.es).toEqual(["Alfa · beta"]);
  });

  it("highlights array v1.1: pasa directo (dual-shape)", () => {
    const r = emptyReport();
    const p = normalize(
      {
        identity: { name: "A B" },
        experience: [
          { role: "R", org: "O", start: "2020-01-01", highlights: { en: ["One", "Two"] } }
        ]
      },
      r
    );
    expect(p.experience[0].highlights?.en).toEqual(["One", "Two"]);
  });

  it("role/org string → langMap {en} + report.missingEs (v1.1 completa el ES)", () => {
    const r = emptyReport();
    const p = normalize(
      { identity: { name: "A B" }, experience: [{ role: "Role", org: "Org", start: "2020-01-01" }] },
      r
    );
    expect(p.experience[0].role).toEqual({ en: "Role" });
    expect(p.experience[0].org).toEqual({ en: "Org" });
    expect(r.missingEs).toContain("experience.role");
    expect(r.missingEs).toContain("experience.org");
  });

  it("publications: url derivada de DOI; sin DOI → url '' (v1.1)", () => {
    const r = emptyReport();
    const raw = {
      identity: { name: "A B" },
      publications: [
        { title: "T1", venue: "V", year: 2026, doi: "10.5281/zenodo.20738795" },
        { title: "T2", venue: "V", year: 2023 }
      ]
    };
    const p = normalize(raw, r);
    expect(p.publications[0].url).toBe("https://doi.org/10.5281/zenodo.20738795");
    expect(p.publications[1].url).toBe("");
  });

  it("driftReport: pub sin DOI → publicationsWithoutLink (regla warn, D12)", () => {
    const raw = {
      identity: { name: "A B" },
      publications: [
        { title: "T1", venue: "V", year: 2026, doi: "10.5281/zenodo.20738795" },
        { title: "T2", venue: "V", year: 2023 }
      ]
    };
    const dr = driftReport(raw as unknown as Record<string, unknown>);
    expect(dr.publicationsWithoutLink).toEqual(["T2"]);
    expect(dr.urlsOutsideIdentity).toEqual([]);
  });

  it("splitName: dado/family desde identity.name", () => {
    const r = emptyReport();
    const p = normalize({ identity: { name: "Christian Luciani" } }, r);
    expect(p.identity.givenName).toBe("Christian");
    expect(p.identity.familyName).toBe("Luciani");
  });

  it("determinismo: dos pasadas del mismo raw → mismo output byte a byte", () => {
    const r = emptyReport();
    const raw = {
      identity: { name: "Christian Luciani", location: "Cuenca, Ecuador" },
      experience: [
        {
          role: "R",
          org: "O",
          start: "2020-01-01",
          end: "present",
          highlights: { en: "A · b. C." }
        }
      ],
      publications: [{ title: "T", venue: "V", year: 2025, doi: "10.1000/xyz" }]
    };
    const a = normalize(raw, emptyReport());
    const b = normalize(raw, emptyReport());
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
    expect((a as CVProfile).identity.givenName).toBe("Christian");
  });
});
