// AUTO-GENERATED by tools/sync-profile.ts — DO NOT EDIT.
// source: profile-data @ 722d2b3ec201b13559098a3dd2f830f83a647c56 · synced 2026-08-16T03:28:31.976Z
// Regenerate: npm run sync:profile  (docs/SPEC.md Fase 1 — editar hechos = editar profile-data)
export const PROFILE = {
  "identity": {
    "name": "Christian Luciani",
    "givenName": "Christian",
    "familyName": "Luciani",
    "location": "Cuenca, Ecuador",
    "photo": "https://lh3.googleusercontent.com/pw/AP1GczO0shri3gqnp7PXfST6iji5bEzrFTzJfnQwKJaGDiLIpGDDWUBgi0eSqW3v79qv63XXBukEWeyWLobOPjLO2NlsJJlyi_A_-KdJtjzJGswIfIank4YA=w500-h500-c",
    "links": [
      {
        "platform": "website",
        "label": "CV — christianluciani.github.io",
        "url": "https://christianluciani.github.io"
      },
      {
        "platform": "email",
        "label": "Email",
        "url": "mailto:cluciani@gmail.com"
      },
      {
        "platform": "whatsapp",
        "label": "WhatsApp",
        "url": "https://wa.me/593993716335"
      },
      {
        "platform": "orcid",
        "label": "ORCID",
        "url": "https://orcid.org/0000-0002-6955-5384"
      },
      {
        "platform": "scholar",
        "label": "Google Scholar",
        "url": "https://scholar.google.com/citations?user=7GbpmSQAAAAJ&hl=en"
      },
      {
        "platform": "github",
        "label": "GitHub",
        "url": "https://github.com/ChristianLuciani"
      },
      {
        "platform": "linkedin",
        "label": "LinkedIn",
        "url": "https://www.linkedin.com/in/christian-luciani"
      },
      {
        "platform": "researchgate",
        "label": "ResearchGate",
        "url": "https://www.researchgate.net/profile/Christian-Luciani"
      },
      {
        "platform": "x",
        "label": "X",
        "url": "https://x.com/cluciani_ve"
      },
      {
        "platform": "instagram",
        "label": "Instagram",
        "url": "https://www.instagram.com/clucianitoledo"
      },
      {
        "platform": "patreon",
        "label": "Patreon",
        "url": "https://www.patreon.com/cluciani"
      },
      {
        "platform": "github",
        "label": "Kontablo — accounting-esperanto",
        "url": "https://github.com/ChristianLuciani/accounting-esperanto"
      },
      {
        "platform": "github",
        "label": "Physics Lab Book",
        "url": "https://github.com/ChristianLuciani/physics-lab-book"
      },
      {
        "platform": "github",
        "label": "Nelson Companion",
        "url": "https://github.com/ChristianLuciani/nelson-companion"
      },
      {
        "platform": "github",
        "label": "Topia",
        "url": "https://github.com/ChristianLuciani/topia"
      },
      {
        "platform": "github",
        "label": "ZENTROPY",
        "url": "https://github.com/ChristianLuciani/ZENTROPY"
      },
      {
        "platform": "github",
        "label": "Esteléctica",
        "url": "https://github.com/ChristianLuciani/estelectica"
      },
      {
        "platform": "github",
        "label": "CLAPPS.AI",
        "url": "https://github.com/ChristianLuciani/clapps-praxia"
      },
      {
        "platform": "github",
        "label": "Drahma — DRAHMAN-ORG",
        "url": "https://github.com/DRAHMAN-ORG/drahman-org"
      }
    ]
  },
  "positioning": {
    "statement": {
      "en": "Physicist with a doctoral candidacy in complex systems and 20+ years navigating scientific research, university teaching and educational innovation.",
      "es": "Físico con candidatura doctoral en sistemas complejos y más de 20 años navegando entre la investigación científica, la docencia universitaria y la innovación educativa."
    },
    "audiences": {
      "recruiters": {
        "en": "Proven across research, university teaching and production systems: X-ray diffractometry operator, 5 co-authored papers, 800+ students per year, 36 original lab guides, and a field-tested educational-AI flagship (Drahma, Aug 2024).",
        "es": "Trayectoria comprobable en investigación, docencia universitaria y sistemas productivos: operador de difractometría de rayos X, 5 papers co-autorados, 800+ estudiantes anuales, 36 guías de laboratorio originales y un flagship de IA educativa probado en campo (Drahma, ago 2024)."
      },
      "clients": {
        "en": "Strategic systems consulting with a sovereign-first approach: BI platforms, ERP (Zoho/ERPNext), cash-audit systems and SaaS architecture — you keep the code and the data.",
        "es": "Consultoría estratégica de sistemas con enfoque soberano: plataformas BI, ERP (Zoho/ERPNext), sistemas de auditoría de efectivo y arquitectura SaaS — el código y los datos son tuyos."
      },
      "peers": {
        "en": "Synthetic-intelligence epistemology: poly-dialectical dialogue, Trunk/Rhizome distillation, and why sovereign, local-first infrastructure is the citability anchor of the agentic economy.",
        "es": "Epistemología de la cognición sintética: diálogo poli-dialéctico, destilación Tronco/Rizoma, y por qué la infraestructura soberana local-first es el ancla de citabilidad de la economía agéntica."
      }
    },
    "geo": {
      "semanticAssociations": [
        "sistemas complejos",
        "cognición sintética",
        "soberanía tecnológica",
        "innovación educativa",
        "open source"
      ],
      "citationsGoal": {
        "en": "Be cited as an authority on synthetic-intelligence education, technological sovereignty and the agentic economy.",
        "es": "Ser citado como autoridad en inteligencia sintética educativa, soberanía tecnológica y economía agéntica."
      }
    }
  },
  "headlines": [
    {
      "platform": "github-readme",
      "lang": "en",
      "text": "Physicist · Complex Systems · Synthetic Intelligence for Education"
    },
    {
      "platform": "linkedin",
      "lang": "en",
      "text": "Physicist | Complex Systems | Synthetic Intelligence for Education | Sovereign Open Source"
    },
    {
      "platform": "linkedin",
      "lang": "es",
      "text": "Físico | Sistemas Complejos | Inteligencia Sintética Educativa | Open Source Soberano"
    },
    {
      "platform": "x",
      "lang": "es",
      "text": "Físico · sistemas complejos · IA educativa · soberanía tecnológica"
    },
    {
      "platform": "upwork",
      "lang": "en",
      "text": "Strategic Systems Consultant — BI, ERP, Cash-Audit & Sovereign AI Infrastructure"
    },
    {
      "platform": "substack",
      "lang": "en",
      "text": "Sovereign AI, the agentic economy & synthetic cognition — with epistemic rigor"
    },
    {
      "platform": "patreon",
      "lang": "en",
      "text": "Support sovereign AI · open source · epistemic rigor"
    }
  ],
  "experience": [
    {
      "role": {
        "en": "Strategic Systems Consultant"
      },
      "org": {
        "en": "Independent — Panama / Ecuador"
      },
      "start": "2025-01-01",
      "end": "present",
      "highlights": {
        "en": [
          "BI platforms and digital infrastructure · Zoho ERP",
          "Cash audit and recording system for a Type C casino (Salsa-Casino)",
          "SaaS architecture for clinical management (see CLAPPS.AI)"
        ],
        "es": [
          "Plataformas BI e infraestructura digital · Zoho ERP",
          "Sistema de auditoría y registro de efectivo para casino tipo C (Salsa-Casino)",
          "Arquitectura SaaS para gestión clínica (ver CLAPPS.AI)"
        ]
      }
    },
    {
      "role": {
        "en": "Physics Laboratory Coordinator"
      },
      "org": {
        "en": "Universidad San Francisco de Quito (USFQ) — Quito, Ecuador"
      },
      "start": "2019-01-01",
      "end": "2024-12-01",
      "highlights": {
        "en": [
          "800+ students per year · 36 original laboratory guides",
          "X-ray diffractometer technician-operator · 5 co-authored publications",
          "Institutional Radiological Safety Officer",
          "USFQ Open House: experiments for the general public"
        ],
        "es": [
          "800+ estudiantes anuales · 36 guías de laboratorio originales",
          "Técnico-operador del difractómetro de rayos X · 5 publicaciones co-autoradas",
          "Responsable de Seguridad Radiológica institucional",
          "Casa Abierta USFQ: experimentos para público general"
        ]
      }
    },
    {
      "role": {
        "en": "Systems Designer / Lighting Technician"
      },
      "org": {
        "en": "Grupo Angel / Fluge-Panamá"
      },
      "start": "2016-01-01",
      "end": "2018-12-01",
      "highlights": {
        "en": [
          "Account-recording and vault system for casinos · auditing procedures",
          "Freelance lighting technician for corporate and entertainment events"
        ],
        "es": [
          "Sistema de registro de cuentas y bóveda para casinos · procedimientos de auditoría",
          "Luminotécnico freelance para eventos corporativos y de entretenimiento"
        ]
      }
    },
    {
      "role": {
        "en": "BTL Logistics & Client Relations"
      },
      "org": {
        "en": "Magic Dreams Productions — Panamá"
      },
      "start": "2010-01-01",
      "end": "2013-12-01",
      "highlights": {
        "en": [
          "Logistics and setup of BTL activations at large-scale events",
          "Clients: Copa Airlines, Visa, ALTA, Cervecería Nacional, Herbalife, BAC Credomatic",
          "Coordination of 1,000 attendees · Panama Christmas Parade 2013",
          "Production: Herbalife Extravaganza 2012",
          "Featured in: Cirque du Soleil, Shakira, Juan Luis Guerra, Jennifer Lopez, Yanni, 2011 Baseball World Cup"
        ],
        "es": [
          "Logística y montaje de activaciones BTL en eventos masivos",
          "Clientes: Copa Airlines, Visa, ALTA, Cervecería Nacional, Herbalife, BAC Credomatic",
          "Coordinación de 1.000 pax · Desfile de Navidad Panamá 2013",
          "Producción: Extravaganza Herbalife 2012",
          "Participación en: Cirque du Soleil, Shakira, Juan Luis Guerra, Jennifer Lopez, Yanni, Copa Mundial de Béisbol 2011"
        ]
      }
    },
    {
      "role": {
        "en": "Photography · Editing · Audiovisual Teaching"
      },
      "org": {
        "en": "Film & TV School — Venezuela"
      },
      "start": "2006-01-01",
      "end": "2010-12-01",
      "highlights": {
        "en": [
          "'La Escalera de Patty' — Prix du Public, FECOVEN 2008",
          "'9 Arepas' — ESPN selection 2008",
          "Editing and montage instructor · Post-production coordinator, Creadores Visuales (2010)"
        ],
        "es": [
          "'La Escalera de Patty' — prix du public, FECOVEN 2008",
          "'9 Arepas' — selección ESPN 2008",
          "Docente de edición y montaje · Coord",
          "post-producción Creadores Visuales (2010)"
        ]
      }
    },
    {
      "role": {
        "en": "Physics Professor"
      },
      "org": {
        "en": "Universidad Simón Bolívar — Caracas"
      },
      "start": "2003-01-01",
      "end": "2006-12-01",
      "highlights": {
        "en": [
          "Labs I, II and III for engineering and sciences (2nd and 3rd year)",
          "Doctoral research in complex systems · first publications"
        ],
        "es": [
          "Laboratorios I, II y III para ingenierías y ciencias (2º y 3er año)",
          "Investigación doctoral en sistemas complejos · primeras publicaciones"
        ]
      }
    },
    {
      "role": {
        "en": "Specialization in Audiovisual Media"
      },
      "org": {
        "en": "Escuela de Cine y TV — Caracas · Prix du Public FECOVEN 2008"
      },
      "start": "2006-01-01",
      "end": "2008-12-01",
      "highlights": {
        "en": [
          "Postgraduate specialization in film and audiovisual media"
        ],
        "es": [
          "Especialización de posgrado en cine y medios audiovisuales"
        ]
      }
    },
    {
      "role": {
        "en": "Doctoral Candidacy — Complex Systems (ABD)"
      },
      "org": {
        "en": "Universidad Simón Bolívar — Venezuela"
      },
      "start": "2003-01-01",
      "end": "2006-12-01",
      "highlights": {
        "en": [
          "All-but-dissertation (ABD)",
          "Thesis pending"
        ],
        "es": [
          "Candidatura doctoral (ABD) — tesis pendiente"
        ]
      }
    },
    {
      "role": {
        "en": "B.Sc. in Physics"
      },
      "org": {
        "en": "Universidad Central de Venezuela · Thesis: N-Dimensional Cosmological Models"
      },
      "start": "1997-01-01",
      "end": "2003-12-01",
      "highlights": {
        "en": [
          "Undergraduate thesis: N-Dimensional Cosmological Models",
          "SENESCYT: 862177536"
        ],
        "es": [
          "Tesis de licenciatura: Modelos Cosmológicos N-Dimensionales",
          "SENESCYT: 862177536"
        ]
      }
    }
  ],
  "education": [],
  "projects": [
    {
      "name": "Kontablo — Universal Accounting Ontology",
      "status": "active",
      "description": {
        "en": "An Esperanto for accounting: graph-based ontology mapping the 195 sovereign jurisdictions to IFRS/XBRL and to the agentic economy (MCP · A2A · AP2). One immutable UUID per universal accounting concept; deterministic three-tier resolution.",
        "es": "Un Esperanto para la contabilidad: ontología basada en grafos que mapea las 195 jurisdicciones soberanas a IFRS/XBRL y a la economía agéntica (MCP · A2A · AP2). Un UUID inamovible por concepto; resolución determinista en tres niveles."
      },
      "links": [
        "https://github.com/ChristianLuciani/accounting-esperanto"
      ],
      "keywords": [
        "contabilidad",
        "accounting",
        "ontología",
        "ontology",
        "grafos",
        "graph database",
        "IFRS/XBRL",
        "economía agéntica",
        "agentic economy",
        "MCP",
        "A2A",
        "AP2"
      ],
      "evidence": [
        {
          "claim": {
            "en": "195 sovereign jurisdictions mapped; 60 statutory chart-of-accounts overlays (56 exercised against primary sources)",
            "es": "195 jurisdicciones soberanas mapeadas; 60 overlays de planes de cuentas estatutarios (56 ejercidos contra fuentes primarias)"
          },
          "source": "https://github.com/ChristianLuciani/accounting-esperanto",
          "verified": "2026-06-30"
        },
        {
          "claim": {
            "en": "Published June 2026 under Business Source License 1.1 (converts to Apache 2.0 in 2030); preprint deposited on Zenodo and SSRN",
            "es": "Publicado en junio 2026 bajo Business Source License 1.1 (convierte a Apache 2.0 en 2030); preprint depositado en Zenodo y SSRN"
          },
          "source": "https://doi.org/10.5281/zenodo.20738795",
          "verified": "2026-06-30"
        }
      ]
    },
    {
      "name": "Drahma — Educational Synthetic Intelligence",
      "status": "active",
      "description": {
        "en": "36 Socratic virtual tutors for the Ecuadorian curriculum, field-tested in the Amazon (Aug 2024) — roughly two months before Khanmigo went public. Built without external funding; model-agnostic via Poe; guardrails for minors.",
        "es": "36 tutores virtuales socráticos para el currículo ecuatoriano, probados en campo amazónico (ago 2024) — aproximadamente dos meses antes de la disponibilidad pública de Khanmigo. Desarrollado sin financiamiento externo; agnóstico del modelo vía Poe; guardrails para menores."
      },
      "links": [
        "https://github.com/DRAHMAN-ORG/drahman-org"
      ],
      "keywords": [
        "tutores socráticos",
        "Socratic tutors",
        "IA educativa",
        "educational AI",
        "currículo ecuatoriano",
        "Ecuadorian curriculum",
        "comunidades amazónicas",
        "Amazon communities",
        "Poe",
        "Khanmigo"
      ],
      "evidence": [
        {
          "claim": {
            "en": "36 Socratic virtual tutors for the Ecuadorian curriculum, field-tested with Amazonian indigenous communities (Aug 2024)",
            "es": "36 tutores virtuales socráticos para el currículo ecuatoriano, probados con comunidades indígenas amazónicas (ago 2024)"
          },
          "source": "https://github.com/DRAHMAN-ORG/drahman-org",
          "verified": "2024-08-31"
        }
      ]
    },
    {
      "name": "ZENTROPY — Zero Entropy Intelligence Station",
      "status": "active",
      "description": {
        "en": "Personal cognitive operating system — captures, distills and organizes synthetic-cognition conversations. Solves dialectical entropy: flashes of clarity that vanish get stored in a structured database (Supabase). Universal ingestion: Claude JSON/ZIP, ChatGPT, Markdown.",
        "es": "Sistema operativo cognitivo personal — captura, destila y organiza conversaciones con cognición sintética. Resuelve la entropía dialéctica: los destellos de claridad se guardan en base de datos estructurada (Supabase). Ingesta universal: Claude JSON/ZIP, ChatGPT, Markdown."
      },
      "links": [
        "https://github.com/ChristianLuciani/ZENTROPY"
      ],
      "keywords": [
        "cognición sintética",
        "synthetic cognition",
        "entropía dialéctica",
        "dialectical entropy",
        "Supabase",
        "multi-tenant",
        "Open WebUI"
      ],
      "evidence": [
        {
          "claim": {
            "en": "Stage 1 complete (operational): structured Supabase schema, universal ingestion (Claude JSON/ZIP, ChatGPT, Markdown), multi-tenant architecture",
            "es": "Stage 1 completo (operacional): schema estructurado en Supabase, ingesta universal (Claude JSON/ZIP, ChatGPT, Markdown), arquitectura multi-tenant"
          },
          "source": "https://github.com/ChristianLuciani/ZENTROPY",
          "verified": "2026-01-15"
        }
      ]
    },
    {
      "name": "Esteléctica — Epistemology of Distilled Poly-dialectical Dialogue",
      "status": "experimental",
      "description": {
        "en": "Philosophical proposal and software architecture about the nature of collective knowledge in the age of synthetic cognition. Trunk/Rhizome model: the rhizome explores freely; the human–synthetic-cognition pair periodically distills toward the Trunk. Integrates Noesis and Noetix.",
        "es": "Propuesta filosófica y arquitectura de software sobre la naturaleza del conocimiento colectivo en la era de la cognición sintética. Modelo Tronco/Rizoma: el rizoma explora libremente; el par humano-cognición sintética destila hacia el Tronco. Integra Noesis y Noetix."
      },
      "links": [
        "https://github.com/ChristianLuciani/estelectica"
      ],
      "keywords": [
        "epistemología",
        "epistemology",
        "diálogo poli-dialéctico",
        "poly-dialectical dialogue",
        "tronco/rizoma",
        "trunk/rhizome",
        "Noesis",
        "Noetix",
        "cognición sintética",
        "synthetic cognition"
      ],
      "evidence": [
        {
          "claim": {
            "en": "Trunk/Rhizome model defined; integrates Noesis (taxonomy of thought perspectives) and Noetix (compound-agent engine)",
            "es": "Modelo Tronco/Rizoma definido; integra Noesis (taxonomía de perspectivas de pensamiento) y Noetix (motor de agentes compuestos)"
          },
          "source": "https://github.com/ChristianLuciani/estelectica",
          "verified": "2026-01-15"
        }
      ]
    },
    {
      "name": "CLAPPS.AI — Comprehensive Learning Applications",
      "status": "planning",
      "description": {
        "en": "Self-taught human-development platform — a counterpoint to the traditional LMS model. Structured, dynamic support for long-term skill development. Closest current reference: NotebookLM, but without structured competency progression.",
        "es": "Plataforma de desarrollo humano autodidacta — contrapunto al modelo LMS tradicional. Soporte estructurado y dinámico para el desarrollo de habilidades a largo plazo. Referente más cercano: NotebookLM, pero sin progresión estructurada de competencias."
      },
      "links": [
        "https://github.com/ChristianLuciani/clapps-praxia"
      ],
      "keywords": [
        "LMS",
        "aprendizaje autodidacta",
        "self-taught learning",
        "competencias",
        "competencies",
        "NotebookLM",
        "educación",
        "education"
      ],
      "evidence": []
    },
    {
      "name": "NOOS — Natural Organization Operating System",
      "status": "experimental",
      "description": {
        "en": "Reduce organizational entropy through distributed synthetic intelligence and knowledge graphs. Organizations modeled as thermodynamic systems with high/low-entropy states. Destination: high-value consulting for organizations in digital transition.",
        "es": "Reducir la entropía organizacional mediante inteligencia sintética distribuida y grafos de conocimiento. Las organizaciones modeladas como sistemas termodinámicos de alta/baja entropía. Destino: consultoría de alto valor para organizaciones en transición digital."
      },
      "links": [],
      "keywords": [
        "entropía organizacional",
        "organizational entropy",
        "grafos de conocimiento",
        "knowledge graphs",
        "sistemas complejos",
        "complex systems",
        "consultoría",
        "consulting"
      ],
      "evidence": []
    },
    {
      "name": "Topia — Newsletter Editorial Engine",
      "status": "planning",
      "description": {
        "en": "From dystopia to achievable eutopias: a newsletter with epistemic rigor — one essay at a time, every claim traced, every thesis falsifiable. Maps the path to technological sovereignty, collective cognition and regenerative economies.",
        "es": "De la distopía a eutopías alcanzables: newsletter con rigor epistémico — un ensayo a la vez, cada claim con fuente, cada tesis falsable. Mapea el camino a la soberanía tecnológica, la cognición colectiva y las economías regenerativas."
      },
      "links": [
        "https://github.com/ChristianLuciani/topia"
      ],
      "keywords": [
        "newsletter",
        "epistemología",
        "epistemology",
        "rigor epistémico",
        "epistemic rigor",
        "eutopías",
        "eutopias"
      ],
      "evidence": []
    },
    {
      "name": "Nelson Companion",
      "status": "active",
      "description": {
        "en": "Voice-guided PWA for my father (76, post-stroke aphasia). Offline-first, zero telemetry.",
        "es": "PWA guiada por voz para mi padre (76, afasia post-ACV). Offline-first, cero telemetría."
      },
      "links": [
        "https://github.com/ChristianLuciani/nelson-companion"
      ],
      "keywords": [
        "PWA",
        "accesibilidad",
        "accessibility",
        "voz",
        "voice",
        "salud",
        "health",
        "offline-first"
      ],
      "evidence": []
    },
    {
      "name": "Physics Lab Book",
      "status": "maintained",
      "description": {
        "en": "36 interactive HTML5 laboratory manuals for university physics — originally written for USFQ (engineering, health sciences, pure sciences).",
        "es": "36 guías interactivas HTML5 de laboratorio de física universitaria — originalmente escritas para USFQ (ingenierías, ciencias de la salud, ciencias puras)."
      },
      "links": [
        "https://github.com/ChristianLuciani/physics-lab-book"
      ],
      "keywords": [
        "física",
        "physics",
        "laboratorio",
        "laboratory",
        "HTML5",
        "educación",
        "education"
      ],
      "evidence": [
        {
          "claim": {
            "en": "800+ students per year served at USFQ; 36 original laboratory guides",
            "es": "800+ estudiantes anuales en USFQ; 36 guías de laboratorio originales"
          },
          "source": "https://github.com/ChristianLuciani/physics-lab-book",
          "verified": "2024-12-01"
        }
      ]
    },
    {
      "name": "Upstream Open Source Contributions",
      "status": "active",
      "description": {
        "en": "Every merged PR is infrastructure that belongs to everyone. Upstream contributions to the agentic-AI ecosystem — AionCore (Pi agent as built-in ACP), pi-acp (session/delete per ACP spec), AionUi (theme-aware logos), Ollama to local ACP agents.",
        "es": "Cada PR mergeado es infraestructura que pertenece a todos. Contribuciones upstream al ecosistema de IA agéntica — AionCore (agente Pi como ACP built-in), pi-acp (session/delete según spec ACP), AionUi (logos theme-aware), Ollama a agentes ACP locales."
      },
      "links": [],
      "keywords": [
        "upstream contributions",
        "open source",
        "AionCore",
        "pi-acp",
        "AionUi",
        "MCP",
        "ACP",
        "soberanía tecnológica",
        "technological sovereignty"
      ],
      "evidence": [
        {
          "claim": {
            "en": "AionCore #618 — Pi agent as built-in ACP (merged)",
            "es": "AionCore #618 — Agente Pi como ACP built-in (mergeado)"
          },
          "source": "https://github.com/iOfficeAI/AionCore/pull/618"
        },
        {
          "claim": {
            "en": "pi-acp #76 — session/delete per ACP spec (merged)",
            "es": "pi-acp #76 — session/delete según spec ACP (mergeado)"
          },
          "source": "https://github.com/svkozak/pi-acp/pull/76"
        },
        {
          "claim": {
            "en": "AionCore #626 — Ollama to local ACP agents (open)",
            "es": "AionCore #626 — Ollama a agentes ACP locales (abierto)"
          },
          "source": "https://github.com/iOfficeAI/AionCore/pull/626"
        },
        {
          "claim": {
            "en": "AionUi #3614 — theme-aware logos (merged)",
            "es": "AionUi #3614 — logos theme-aware (mergeado)"
          },
          "source": "https://github.com/iOfficeAI/AionUi/pull/3614"
        }
      ]
    }
  ],
  "publications": [
    {
      "title": "Kontablo: A Graph-Based Universal Accounting Ontology for the M2M Agentic Economy",
      "venue": "Preprint — Zenodo & SSRN (not yet peer-reviewed)",
      "year": 2026,
      "doi": "10.5281/zenodo.20738795",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.5281/zenodo.20738795"
    },
    {
      "title": "Highly efficient caffeine-based PVA composite film for UV shielding",
      "venue": "Carbon Trends",
      "year": 2025,
      "doi": "10.1016/j.cartre.2025.100502",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.1016/j.cartre.2025.100502"
    },
    {
      "title": "Tunable Dielectric Carbon Materials from Hydrothermally Nanostructured Organic Carbon Sources",
      "venue": "ChemPhysChem",
      "year": 2025,
      "doi": "10.1002/cphc.202400711",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.1002/cphc.202400711"
    },
    {
      "title": "Optimization of microfibrillated cellulose isolation from cocoa pod husk via mild oxalic acid hydrolysis",
      "venue": "Heliyon",
      "year": 2023,
      "doi": "10.1016/j.heliyon.2023.e17258",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.1016/j.heliyon.2023.e17258"
    },
    {
      "title": "Hydrochars from Lignocellulosic Residues for Green Electronics, Environmental Remediation, Energy and Agricultural Applications",
      "venue": "ResearchGate preprint",
      "year": 2023,
      "orcidId": "0000-0002-6955-5384",
      "url": ""
    },
    {
      "title": "Optimization of Microcrystalline Cellulose Isolation from Cocoa Pod Husk via Mild Oxalic Acid Hydrolysis",
      "venue": "SSRN Electronic Journal",
      "year": 2022,
      "doi": "10.2139/ssrn.4307097",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.2139/ssrn.4307097"
    },
    {
      "title": "Ivory Nut (Phytelephas equatorialis) Residues: Chemical Composition for Applications in Health Care, Industry and Environmental Remediation — Towards Sustainability",
      "venue": "2022 AIChE Annual Meeting (abstract)",
      "year": 2022,
      "orcidId": "0000-0002-6955-5384",
      "url": ""
    },
    {
      "title": "Neural control on multiple time scales: Insights from human stick balancing",
      "venue": "Condensed Matter Physics",
      "year": 2006,
      "doi": "10.5488/CMP.9.2.373",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.5488/CMP.9.2.373"
    },
    {
      "title": "Balancing with Noise and Delay",
      "venue": "Progress of Theoretical Physics Supplement",
      "year": 2006,
      "doi": "10.1143/PTPS.161.314",
      "orcidId": "0000-0002-6955-5384",
      "url": "https://doi.org/10.1143/PTPS.161.314"
    }
  ],
  "skills": [
    {
      "name": "Synthetic Intelligence / Agents",
      "level": "advanced",
      "keywords": [
        "agent orchestration",
        "synthetic cognition",
        "MCP",
        "ACP",
        "A2A",
        "Socratic tutors",
        "RAG context engineering"
      ],
      "geoKeywords": [
        "cognición sintética",
        "inteligencia sintética educativa"
      ],
      "platformWeights": {
        "github-readme": 0.9,
        "linkedin": 0.9,
        "upwork": 0.8,
        "x": 0.8
      }
    },
    {
      "name": "Agentic Coding",
      "level": "advanced",
      "keywords": [
        "agent-guided development",
        "SPEC + TDD with agents",
        "AI-assisted maintenance"
      ],
      "platformWeights": {
        "github-readme": 1,
        "upwork": 0.8,
        "x": 0.6
      }
    },
    {
      "name": "Technological Sovereignty",
      "level": "expert",
      "keywords": [
        "self-hosting",
        "LiteLLM / Ollama",
        "ERPNext",
        "privacy and data ownership",
        "Linux / macOS"
      ],
      "geoKeywords": [
        "soberanía tecnológica",
        "inferencia soberana"
      ],
      "platformWeights": {
        "github-readme": 0.9,
        "x": 0.7,
        "linkedin": 0.6
      }
    },
    {
      "name": "Open Source",
      "level": "advanced",
      "keywords": [
        "upstream contributions",
        "AionCore (Pi as built-in ACP)",
        "pi-acp (session/delete)",
        "BSL 1.1 → Apache 2.0"
      ],
      "platformWeights": {
        "github-readme": 1,
        "linkedin": 0.5
      }
    },
    {
      "name": "Platforms & Ecosystem",
      "level": "intermediate",
      "keywords": [
        "ERPNext",
        "Zoho ERP",
        "Supabase",
        "Chatwoot",
        "Poe"
      ],
      "platformWeights": {
        "upwork": 0.7,
        "github-readme": 0.4
      }
    },
    {
      "name": "Sciences — Physics",
      "level": "expert",
      "keywords": [
        "sistemas complejos",
        "X-ray diffractometry",
        "radiological safety",
        "experimental physics"
      ],
      "geoKeywords": [
        "sistemas complejos",
        "difractometría de rayos X"
      ],
      "platformWeights": {
        "researchgate": 1,
        "linkedin": 0.7,
        "github-readme": 0.5
      }
    }
  ],
  "languages": [],
  "keywords": {
    "seo": {
      "github": [
        "sovereign AI infrastructure",
        "agentic coding",
        "universal accounting ontology",
        "educational synthetic intelligence",
        "open source"
      ],
      "linkedin": [
        "physicist complex systems",
        "synthetic intelligence education",
        "educational AI Ecuador",
        "open source sovereign"
      ],
      "upwork": [
        "strategic systems consultant",
        "BI platforms ERP",
        "cash audit systems",
        "SaaS architecture",
        "sovereign AI infrastructure"
      ],
      "x": [
        "física sistemas complejos",
        "cognición sintética",
        "IA educativa",
        "soberanía tecnológica"
      ],
      "researchgate": [
        "complex systems",
        "X-ray diffractometry",
        "cellulose nanocrystals",
        "universal accounting ontology"
      ],
      "substack": [
        "sovereign AI",
        "agentic economy",
        "epistemology of synthetic cognition",
        "epistemic rigor"
      ]
    },
    "geo": {
      "associations": [
        "sistemas complejos",
        "cognición sintética",
        "soberanía tecnológica",
        "innovación educativa",
        "open source",
        "economía agéntica",
        "IA educativa"
      ],
      "claims": [
        "36 tutores virtuales socráticos para el currículo ecuatoriano, probados en campo amazónico (ago 2024)",
        "800+ estudiantes anuales y 36 guías de laboratorio originales (USFQ, 2019–2024)",
        "195 jurisdicciones soberanas mapeadas (Kontablo)",
        "10 publicaciones/preprints 2006–2026, 6 con DOI resoluble",
        "5 publicaciones co-autoradas como operador de difractometría de rayos X",
        "4 upstream PRs (3 merged): AionCore #618 (Pi como ACP built-in), pi-acp #76 (session/delete), AionCore #626 (Ollama → ACP local), AionUi #3614 (logos theme-aware)"
      ]
    }
  },
  "source": {
    "repo": "https://github.com/ChristianLuciani/profile-data.git",
    "commit": "722d2b3ec201b13559098a3dd2f830f83a647c56",
    "syncedAt": "2026-08-20T14:30:00.000Z"
  }
} as const;
